- name: "Build Attestation Service"
  # shell: ./scripts/accli_wrapper.sh attestation-service run --rebuild --background --overwrite-external-ip {{ as_ip }}
  shell: ./scripts/accli_wrapper.sh attestation-service build
  args:
    chdir: "/home/{{ ansible_user }}/git/faasm/accless"
    executable: /bin/bash
  environment:
    PATH: "/home/{{ ansible_user }}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# TODO: run attestation-service
