- name: "Install APT depdencencies"
  become: yes
  apt:
    name:
      - build-essential
      - libfontconfig1-dev
      - libtss2-dev
      - libtss2-sys1t64
      - libssl-dev
      - pkg-config
      - python3-venv
    update_cache: yes
